image: projectsforge/buildbase

stages:
  - build
  - test
  - deploy

cache:
  key: "ALL"
  paths:
    - .m2
    - .sdkman

before_script:
  - # allow caching sdkman downloads
  - sudo rmdir /opt/sdkman/archives && mkdir -p .sdkman && sudo ln -s `pwd`/.sdkman /opt/sdkman/archives
  - # allow caching maven downloads
  - sudo rm -rf /home/user/.m2 && mkdir -p .m2 && sudo ln -s `pwd`/.m2 /home/user/.m2
  - sdkw install java
  - source "$SDKMAN_DIR/bin/sdkman-init.sh"
  # remove any previously deployed artifact
  - rm -rf .m2/repository/org/projectsforge/
  - mkdir -p ~/.ssh
  - ssh-keyscan -p 2223 static.projectsforge.org > ~/.ssh/known_hosts
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | ssh-add - 

# build of master
build_job:
  stage: build
  only:
    - master
  script:
    - sudo chmod +x mvnw
    - ./mvnw --batch-mode compile -Dmaven.test.skip=true -Djacoco.skip=true -Dmaven.javadoc.skip=true -Dmaven.source.skip=true
  tags:
    - docker

# build of the current branch state applied on latest state of the master branch
build_merge_job:
  stage: build
  except:
    - master
    - tags
  script:
    - git config user.email "gitlab@projectsforge.org"
    - git config user.name "GitLab CI"
    - git merge origin master --no-commit --no-ff
    # allow caching sdkman downloads
    - sudo chmod +x mvnw
    - ./mvnw --batch-mode compile -Dmaven.test.skip=true -Djacoco.skip=true -Dmaven.javadoc.skip=true -Dmaven.source.skip=true
  tags:
    - docker

# deploy master (should be a SNAPSHOT)
deploy_job:
  stage: deploy
  only:
    - master
  script:
    - sudo chmod +x mvnw
    - ./mvnw --batch-mode deploy -Dmaven.test.skip=true -Djacoco.skip=true
  tags:
    - docker

# deploy a tag as a release
deploy_tags_job:
  stage: deploy
  only:
    - tags
  script:
    - sudo chmod +x mvnw
    - ./mvnw --batch-mode org.codehaus.mojo:versions-maven-plugin:2.1:set -DnewVersion=$CI_BUILD_TAG -DgenerateBackupPoms=false
    - ./mvnw --batch-mode clean deploy -Dmaven.test.skip=true -Djacoco.skip=true 
  tags:
    - docker




